<?php
/*
* Config file with each demo data
*/

return array(
	'agency-demo'	=>	array(
		'demoName'				=>	'Agency Demo',
		'liveURL'				=>	'http://highgradelab.com/upshot/agency-demo/',
		'demoImg'				=>	'agency.jpg',
		'xmlContentFile'		=>	'agency-demo.xml',
		'themeOptionsFile'		=>	'agency-demo.json',
		'essentialGridFile'		=>	array('agency-demo.json'),
		'revSliderZipFiles'		=>	false,
	),
	'corporate-demo'	=>	array(
		'demoName'				=>	'Corporate Demo',
		'liveURL'				=>	'http://highgradelab.com/upshot/corporate-demo/',
		'demoImg'				=>	'corporate.jpg',
		'xmlContentFile'		=>	'corporate-demo.xml',
		'themeOptionsFile'		=>	'corporate-demo.json',
		'essentialGridFile'		=>	false,
		'revSliderZipFiles'		=>	false,
	),
	'business-demo'	=>	array(
		'demoName'				=>	'Business Demo',
		'liveURL'				=>	'http://highgradelab.com/upshot/business-demo/',
		'demoImg'				=>	'business.jpg',
		'xmlContentFile'		=>	'business-demo.xml',
		'themeOptionsFile'		=>	'business-demo.json',
		'essentialGridFile'		=>	array('business-demo.json'),
		'revSliderZipFiles'		=>	false,
	),
	'conference-demo'	=>	array(
		'demoName'				=>	'Conference Demo',
		'liveURL'				=>	'http://highgradelab.com/upshot/conference-demo/',
		'demoImg'				=>	'conference.jpg',
		'xmlContentFile'		=>	'conference-demo.xml',
		'themeOptionsFile'		=>	'conference-demo.json',
		'essentialGridFile'		=>	false,
		'revSliderZipFiles'		=>	false,
	),
	'creative-agency-demo'	=>	array(
		'demoName'				=>	'Creative Agency Demo',
		'liveURL'				=>	'http://highgradelab.com/upshot/creative-agency-demo/',
		'demoImg'				=>	'creative-agency.jpg',
		'xmlContentFile'		=>	'creative-agency-demo.xml',
		'themeOptionsFile'		=>	'creative-agency-demo.json',
		'essentialGridFile'		=>	array('creative-agency-demo.json'),
		'revSliderZipFiles'		=>	false,
	),
	'simple-business-demo'	=>	array(
		'demoName'				=>	'Simple Business Demo',
		'liveURL'				=>	'http://highgradelab.com/upshot/simple-business-demo/',
		'demoImg'				=>	'simple-business.jpg',
		'xmlContentFile'		=>	'simple-business-demo.xml',
		'themeOptionsFile'		=>	'simple-business-demo.json',
		'essentialGridFile'		=>	false,
		'revSliderZipFiles'		=>	false,
	),
	'shop-demo'	=>	array(
		'demoName'				=>	'Shop Demo',
		'liveURL'				=>	'http://highgradelab.com/upshot/shop-demo/',
		'demoImg'				=>	'shop.jpg',
		'xmlContentFile'		=>	'shop-demo.xml',
		'themeOptionsFile'		=>	'shop-demo.json',
		'essentialGridFile'		=>	array('shop-demo.json'),
		'revSliderZipFiles'		=>	array('web-product-light.zip'),
	),
	'startup-demo'	=>	array(
		'demoName'				=>	'Startup Demo',
		'liveURL'				=>	'http://highgradelab.com/upshot/startup-demo/',
		'demoImg'				=>	'startup.jpg',
		'xmlContentFile'		=>	'startup-demo.xml',
		'themeOptionsFile'		=>	'startup-demo.json',
		'essentialGridFile'		=>	false,
		'revSliderZipFiles'		=>	false,
	),
	'small-business-demo'	=>	array(
		'demoName'				=>	'Small Business Demo',
		'liveURL'				=>	'http://highgradelab.com/upshot/small-business-demo/',
		'demoImg'				=>	'small-business.jpg',
		'xmlContentFile'		=>	'small-business-demo.xml',
		'themeOptionsFile'		=>	'small-business-demo.json',
		'essentialGridFile'		=>	false,
		'revSliderZipFiles'		=>	false,
	),
	'small-agency-demo'	=>	array(
		'demoName'				=>	'Small Agency Demo',
		'liveURL'				=>	'http://highgradelab.com/upshot/small-agency-demo/',
		'demoImg'				=>	'small-agency.jpg',
		'xmlContentFile'		=>	'small-agency-demo.xml',
		'themeOptionsFile'		=>	'small-agency-demo.json',
		'essentialGridFile'		=>	false,
		'revSliderZipFiles'		=>	false,
	),
	'digital-agency'	=>	array(
		'demoName'				=>	'Digital Agency',
		'liveURL'				=>	'http://highgradelab.com/upshot/digital-agency/',
		'demoImg'				=>	'digital-agency.jpg',
		'xmlContentFile'		=>	'digital-agency.xml',
		'themeOptionsFile'		=>	'digital-agency.json',
		'essentialGridFile'		=>	false,
		'revSliderZipFiles'		=>	false,
	),
	'parallax-landing-page'	=>	array(
		'demoName'				=>	'Parallax Landing Page',
		'liveURL'				=>	'http://highgradelab.com/upshot/parallax-landing-page-demo/',
		'demoImg'				=>	'parallax-landing-page.jpg',
		'xmlContentFile'		=>	'parallax-landing-page.xml',
		'themeOptionsFile'		=>	'parallax-landing-page.json',
		'essentialGridFile'		=>	false,
		'revSliderZipFiles'		=>	false,
	),
	'freelancer'	=>	array(
		'demoName'				=>	'Freelancer Demo',
		'liveURL'				=>	'http://highgradelab.com/upshot/freelancer-demo/',
		'demoImg'				=>	'freelancer.jpg',
		'xmlContentFile'		=>	'freelancer.xml',
		'themeOptionsFile'		=>	'freelancer.json',
		'essentialGridFile'		=>	false,
		'revSliderZipFiles'		=>	false,
	),
	'landing-page'	=>	array(
		'demoName'				=>	'Landing Page',
		'liveURL'				=>	'http://highgradelab.com/upshot/landing-page/',
		'demoImg'				=>	'landing-page.jpg',
		'xmlContentFile'		=>	'landing-page.xml',
		'themeOptionsFile'		=>	'landing-page.json',
		'essentialGridFile'		=>	false,
		'revSliderZipFiles'		=>	false,
	),
	'minimal-shop'	=>	array(
		'demoName'				=>	'Minimal Shop',
		'liveURL'				=>	'http://highgradelab.com/upshot/minimal-shop/',
		'demoImg'				=>	'minimal-shop.jpg',
		'xmlContentFile'		=>	'minimal-shop.xml',
		'themeOptionsFile'		=>	'minimal-shop.json',
		'essentialGridFile'		=>	array('minimal-shop.json'),
		'revSliderZipFiles'		=>	false,
	),
	'fashion-shop'	=>	array(
		'demoName'				=>	'Fashion Shop',
		'liveURL'				=>	'http://highgradelab.com/upshot/fashion-shop/',
		'demoImg'				=>	'fashion-shop.jpg',
		'xmlContentFile'		=>	'fashion-shop.xml',
		'themeOptionsFile'		=>	'fashion-shop.json',
		'essentialGridFile'		=>	array('fashion-shop.json'),
		'revSliderZipFiles'		=>	false,
	),
	'multishop'	=>	array(
		'demoName'				=>	'MultiShop',
		'liveURL'				=>	'http://highgradelab.com/upshot/multishop/',
		'demoImg'				=>	'multishop.jpg',
		'xmlContentFile'		=>	'multishop.xml',
		'themeOptionsFile'		=>	'multishop.json',
		'essentialGridFile'		=>	array('multishop.json'),
		'revSliderZipFiles'		=>	false,
	),
	'company-presentation'	=>	array(
		'demoName'				=>	'Company Presentation',
		'liveURL'				=>	'http://highgradelab.com/upshot/company-presentation/',
		'demoImg'				=>	'company-presentation.jpg',
		'xmlContentFile'		=>	'company-presentation.xml',
		'themeOptionsFile'		=>	'company-presentation.json',
		'essentialGridFile'		=>	false,
		'revSliderZipFiles'		=>	array('Intro.zip'),
	),
	'pages'	=>	array(
		'demoName'				=>	'All Pages',
		'liveURL'				=>	'http://highgradelab.com/upshot/',
		'demoImg'				=>	'pages.jpg',
		'xmlContentFile'		=>	'pages.xml',
		'themeOptionsFile'		=>	'pages.json',
		'essentialGridFile'		=>	false,
		'revSliderZipFiles'		=>	false,
	)
	
)
?>